#cloud-config
package_update: true
package_upgrade: true
packages:
  - docker.io
  - docker-compose
runcmd:
  - modprobe br_netfilter && echo '1' > /proc/sys/net/ipv4/ip_forward
  # Disable the annoying motd
  - sed -i s/ENABLED=1/ENABLED=0/g /etc/default/motd-news
  - chmod -x /etc/update-motd.d/80-livepatch
  - chmod -x /etc/update-motd.d/10-help-text

system_info:
  default_user:
    name: ${DEFAULT_USER}
ssh_authorized_keys:
  - ${SSH_PUB_KEY}
users:
  - name: ${DEFAULT_USER}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - ${SSH_PUB_KEY}
groups:
  - docker

write_files:
  - path: "/home/student/docker-compose.yml"
    permissions: "0744"
    content: |
      version: '3'

      services:
        nginx:
          image: nginx:1.21.4
          volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
          ports:
            - "80:80"
        %{ for name, instance_info in INSTANCES }
        wetty-${name}:
          image: wettyoss/wetty # FIXME: pin?
          volumes:
            - ./keys/${instance_info["student"]}:/keys/key
          command: --ssh-host=${instance_info["ip"]} --ssh-auth=publickey --ssh-user=student --ssh-key /keys/key --base=/${name}
        %{ endfor }
  - path: "/home/student/nginx.conf"
    permissions: "0744"
    content: |
      events { worker_connections 1024; }

      http {

        server {
          listen 80;

        %{ for name, instance_info in INSTANCES }
          location ^~ /${name} {
            proxy_pass http://wetty-mbischoff-cp:3000/${name};
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 43200000;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_set_header X-NginX-Proxy true;
          }
        %{ endfor }
        }
      }
  %{ for name, keys in SSH_KEYS }
  - ${jsonencode ({"content"=keys[0],"path"="/home/student/keys/${name}","permissions"="0600"})}
  %{ endfor }
