version: '3'
services:
  nginx:
    image: nginx:1.21.4
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./htpasswd/:/conf/htpasswd/:ro
    ports:
      - "80:80"
  %{ for name, instance_info in INSTANCES }
  wetty-${name}:
    image: wettyoss/wetty # FIXME: pin?
    volumes:
      - ./keys/${instance_info["student"]}:/keys/key
    command: --ssh-host=${instance_info["ip"]} --ssh-auth=publickey --ssh-user=student --ssh-key /keys/key --base=/${name}
  %{ endfor }
